apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecompilot

resources:
  - cert-manager.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: ecompilot
  app.kubernetes.io/component: ingress
