// ─────────────────────────────────────────────────────────────────────────────
// EcomPilot PL — suppliers-service seed data
// 20+ sample suppliers across all types: china, poland, turkey, eu, dropship
// Run: tsx src/db/seed.ts
// ─────────────────────────────────────────────────────────────────────────────

import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import { suppliers } from "./schema.js";
import type { NewSupplier } from "./schema.js";

const { Pool } = pg;

const DATABASE_URL = process.env["DATABASE_URL"];
if (!DATABASE_URL) {
  process.stderr.write("DATABASE_URL environment variable is required\n");
  process.exit(1);
}

const pool = new Pool({ connectionString: DATABASE_URL, max: 5 });
const db = drizzle(pool);

// ─────────────────────────────────────────────────────────────────────────────
// Seed data
// ─────────────────────────────────────────────────────────────────────────────

const SEED_SUPPLIERS: NewSupplier[] = [
  // ─── CHINA suppliers ──────────────────────────────────────────────────────
  {
    name: "Guangzhou Fashion Hub",
    slug: "guangzhou-fashion-hub",
    type: "china",
    country: "CN",
    website: "https://guangzhou-fashion-hub.example.com",
    logoUrl: null,
    description: {
      ru: "Крупный поставщик модной одежды из Гуанчжоу с более чем 10 000 SKU.",
      pl: "Duży dostawca odzieży modowej z Guangzhou z ponad 10 000 SKU.",
      ua: "Великий постачальник модного одягу з Гуанчжоу з понад 10 000 SKU.",
      en: "Large fashion clothing supplier from Guangzhou with 10,000+ SKUs.",
    },
    minimumOrderEur: 200,
    categories: ["clothing", "fashion", "women-fashion", "accessories"],
    platforms: ["1688", "alibaba"],
    supportsDropship: false,
    isVerified: true,
    rating: "4.70",
    reviewCount: 142,
    languages: ["zh", "en"],
    contacts: { email: "sales@guangzhou-fashion-hub.example.com", whatsapp: "+8613800000001" },
    shippingInfo: {
      methods: ["DHL", "UPS", "sea-freight"],
      regionsServed: ["PL", "EU"],
      averageDaysToPoland: 14,
      freeShippingAboveEur: 500,
    },
    partnerCommissionPct: "8.00",
    tags: ["clothing", "women", "fashion", "wholesale", "guangzhou"],
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Shenzhen Electronics Pro",
    slug: "shenzhen-electronics-pro",
    type: "china",
    country: "CN",
    website: "https://shenzhen-electronics-pro.example.com",
    description: {
      ru: "Поставщик электроники и гаджетов напрямую с заводов Шэньчжэня.",
      pl: "Dostawca elektroniki i gadżetów bezpośrednio z fabryk Shenzhen.",
      en: "Electronics and gadget supplier direct from Shenzhen factories.",
    },
    minimumOrderEur: 500,
    categories: ["electronics", "gadgets", "smart-home", "cables"],
    platforms: ["1688", "alibaba"],
    supportsDropship: false,
    isVerified: true,
    rating: "4.50",
    reviewCount: 89,
    languages: ["zh", "en"],
    contacts: { email: "b2b@shenzhen-electronics-pro.example.com" },
    shippingInfo: {
      methods: ["DHL", "FedEx", "air-freight"],
      regionsServed: ["PL", "EU", "US"],
      averageDaysToPoland: 10,
    },
    partnerCommissionPct: "6.00",
    tags: ["electronics", "gadgets", "shenzhen", "technology"],
    isActive: true,
    isFeatured: false,
  },
  {
    name: "Yiwu Accessories World",
    slug: "yiwu-accessories-world",
    type: "china",
    country: "CN",
    website: "https://yiwu-accessories.example.com",
    description: {
      ru: "Аксессуары оптом с рынка Иу: украшения, сумки, ремни, кошельки.",
      pl: "Akcesoria hurtowo z rynku Yiwu: biżuteria, torebki, paski, portfele.",
      en: "Wholesale accessories from Yiwu market: jewelry, bags, belts, wallets.",
    },
    minimumOrderEur: 100,
    categories: ["accessories", "jewelry", "bags", "belts"],
    platforms: ["1688"],
    supportsDropship: true,
    isVerified: false,
    rating: "4.20",
    reviewCount: 34,
    languages: ["zh", "en"],
    contacts: { whatsapp: "+8613900000003", email: "order@yiwu-accessories.example.com" },
    shippingInfo: {
      methods: ["China Post", "DHL"],
      regionsServed: ["PL", "EU"],
      averageDaysToPoland: 21,
    },
    partnerCommissionPct: "10.00",
    tags: ["accessories", "jewelry", "yiwu", "wholesale", "dropship"],
    isActive: true,
    isFeatured: false,
  },
  {
    name: "Hangzhou Home Decor",
    slug: "hangzhou-home-decor",
    type: "china",
    country: "CN",
    website: "https://hangzhou-home-decor.example.com",
    description: {
      ru: "Декор для дома и садовые товары от производителей Ханчжоу.",
      pl: "Dekoracje domowe i artykuły ogrodowe od producentów z Hangzhou.",
      en: "Home decor and garden products from Hangzhou manufacturers.",
    },
    minimumOrderEur: 300,
    categories: ["home-decor", "garden", "furniture", "lighting"],
    platforms: ["alibaba"],
    supportsDropship: false,
    isVerified: true,
    rating: "4.60",
    reviewCount: 67,
    languages: ["zh", "en"],
    contacts: { email: "export@hangzhou-home-decor.example.com" },
    shippingInfo: {
      methods: ["sea-freight", "air-freight"],
      regionsServed: ["PL", "EU"],
      averageDaysToPoland: 30,
      freeShippingAboveEur: 1000,
    },
    partnerCommissionPct: "7.50",
    tags: ["home-decor", "furniture", "hangzhou", "garden"],
    isActive: true,
    isFeatured: false,
  },
  {
    name: "Canton Toys & Kids",
    slug: "canton-toys-kids",
    type: "china",
    country: "CN",
    website: "https://canton-toys.example.com",
    description: {
      ru: "Детские игрушки и товары для детей — прямо с завода в Дунгуане.",
      pl: "Zabawki i artykuły dziecięce prosto z fabryki w Dongguan.",
      en: "Children's toys and kids products direct from Dongguan factory.",
    },
    minimumOrderEur: 250,
    categories: ["toys", "kids", "baby", "educational"],
    platforms: ["1688", "alibaba"],
    supportsDropship: false,
    isVerified: false,
    rating: "4.10",
    reviewCount: 22,
    languages: ["zh", "en"],
    contacts: { email: "toys@canton-kids.example.com" },
    shippingInfo: {
      methods: ["DHL", "sea-freight"],
      regionsServed: ["PL", "EU"],
      averageDaysToPoland: 18,
    },
    partnerCommissionPct: "9.00",
    tags: ["toys", "kids", "baby", "dongguan", "educational"],
    isActive: true,
    isFeatured: false,
  },

  // ─── POLAND suppliers ─────────────────────────────────────────────────────
  {
    name: "Polskie Textilia Sp. z o.o.",
    slug: "polskie-textilia",
    type: "poland",
    country: "PL",
    website: "https://polskie-textilia.example.pl",
    description: {
      ru: "Польский производитель текстиля: постельное белье, полотенца, ткани.",
      pl: "Polski producent tekstyliów: pościel, ręczniki, tkaniny domowe.",
      ua: "Польський виробник текстилю: постільна білизна, рушники, тканини.",
      en: "Polish textile manufacturer: bed linen, towels, home fabrics.",
    },
    minimumOrderEur: 150,
    categories: ["textiles", "home-textiles", "bedding", "towels"],
    platforms: ["allegro"],
    supportsDropship: true,
    hasBaselinkerId: "POL-TEXT-001",
    isVerified: true,
    rating: "4.80",
    reviewCount: 201,
    languages: ["pl", "en", "ru"],
    contacts: { email: "hurt@polskie-textilia.example.pl", phone: "+48221234567" },
    shippingInfo: {
      methods: ["DPD", "InPost", "GLS"],
      regionsServed: ["PL", "EU"],
      averageDaysToPoland: 2,
      freeShippingAboveEur: 200,
    },
    partnerCommissionPct: "12.00",
    tags: ["textiles", "poland", "bedding", "wholesale", "dropship"],
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Łódź Odzież Hurtownia",
    slug: "lodz-odziez-hurtownia",
    type: "poland",
    country: "PL",
    website: "https://lodz-odziez.example.pl",
    description: {
      ru: "Оптовая торговля одеждой из Лодзи — широкий ассортимент для всей семьи.",
      pl: "Hurtownia odzieży z Łodzi — szeroki asortyment odzieży dla całej rodziny.",
      en: "Łódź clothing wholesale — wide range of family clothing.",
    },
    minimumOrderEur: 200,
    categories: ["clothing", "fashion", "men-fashion", "women-fashion", "kids"],
    platforms: ["allegro"],
    supportsDropship: false,
    isVerified: true,
    rating: "4.40",
    reviewCount: 88,
    languages: ["pl", "en"],
    contacts: { email: "zamowienia@lodz-odziez.example.pl", phone: "+48421234567" },
    shippingInfo: {
      methods: ["InPost", "DPD"],
      regionsServed: ["PL"],
      averageDaysToPoland: 1,
    },
    partnerCommissionPct: "11.00",
    tags: ["clothing", "lodz", "poland", "wholesale", "family"],
    isActive: true,
    isFeatured: false,
  },
  {
    name: "EcoHealth Polska",
    slug: "ecohealth-polska",
    type: "poland",
    country: "PL",
    website: "https://ecohealth-polska.example.pl",
    description: {
      ru: "Польские органические продукты здоровья и красоты — сертифицированные.",
      pl: "Polskie organiczne produkty zdrowia i urody — certyfikowane.",
      en: "Polish certified organic health and beauty products.",
    },
    minimumOrderEur: 100,
    categories: ["health", "beauty", "organic", "supplements"],
    platforms: ["allegro"],
    supportsDropship: true,
    hasBaselinkerId: "ECO-PL-002",
    isVerified: true,
    rating: "4.90",
    reviewCount: 315,
    languages: ["pl", "en"],
    contacts: { email: "b2b@ecohealth-polska.example.pl", telegram: "@ecohealthpl" },
    shippingInfo: {
      methods: ["InPost", "Pocztex", "DPD"],
      regionsServed: ["PL", "EU"],
      averageDaysToPoland: 1,
      freeShippingAboveEur: 150,
    },
    partnerCommissionPct: "15.00",
    tags: ["health", "beauty", "organic", "poland", "dropship"],
    isActive: true,
    isFeatured: true,
  },

  // ─── TURKEY suppliers ─────────────────────────────────────────────────────
  {
    name: "Istanbul Leather Co.",
    slug: "istanbul-leather-co",
    type: "turkey",
    country: "TR",
    website: "https://istanbul-leather.example.com",
    description: {
      ru: "Турецкий производитель кожаных изделий: сумки, куртки, ремни.",
      pl: "Turecki producent wyrobów skórzanych: torebki, kurtki, paski.",
      en: "Turkish leather goods manufacturer: bags, jackets, belts.",
    },
    minimumOrderEur: 300,
    categories: ["leather-goods", "bags", "fashion", "accessories"],
    platforms: [],
    supportsDropship: false,
    isVerified: true,
    rating: "4.60",
    reviewCount: 73,
    languages: ["tr", "en"],
    contacts: { email: "export@istanbul-leather.example.com", whatsapp: "+905001234567" },
    shippingInfo: {
      methods: ["DHL", "UPS", "Turkish Cargo"],
      regionsServed: ["PL", "EU"],
      averageDaysToPoland: 7,
      freeShippingAboveEur: 600,
    },
    partnerCommissionPct: "8.50",
    tags: ["leather", "turkey", "istanbul", "bags", "fashion"],
    isActive: true,
    isFeatured: false,
  },
  {
    name: "Ankara Textil Export",
    slug: "ankara-textil-export",
    type: "turkey",
    country: "TR",
    website: "https://ankara-textil-export.example.com",
    description: {
      ru: "Экспорт турецкого текстиля — оптовые поставки хлопкового белья и одежды.",
      pl: "Eksport tureckiego tekstylu — hurtowe dostawy bawełnianej bielizny i odzieży.",
      en: "Turkish textile export — wholesale cotton underwear and clothing supply.",
    },
    minimumOrderEur: 400,
    categories: ["textiles", "clothing", "underwear", "cotton"],
    platforms: [],
    supportsDropship: false,
    isVerified: true,
    rating: "4.30",
    reviewCount: 41,
    languages: ["tr", "en", "ru"],
    contacts: { email: "sales@ankara-textil.example.com", telegram: "@ankara_textil" },
    shippingInfo: {
      methods: ["DHL", "air-freight"],
      regionsServed: ["PL", "EU", "RU"],
      averageDaysToPoland: 5,
    },
    partnerCommissionPct: "9.00",
    tags: ["textiles", "turkey", "ankara", "cotton", "wholesale"],
    isActive: true,
    isFeatured: false,
  },
  {
    name: "Bursa Silk & Fashion",
    slug: "bursa-silk-fashion",
    type: "turkey",
    country: "TR",
    website: "https://bursa-silk.example.com",
    description: {
      ru: "Шелковые ткани и высокая мода из Бурсы — столицы шелка Турции.",
      pl: "Tkaniny jedwabne i haute couture z Bursy — stolicy jedwabiu Turcji.",
      en: "Silk fabrics and high fashion from Bursa — the silk capital of Turkey.",
    },
    minimumOrderEur: 500,
    categories: ["silk", "fashion", "fabrics", "luxury"],
    platforms: [],
    supportsDropship: false,
    isVerified: true,
    rating: "4.75",
    reviewCount: 29,
    languages: ["tr", "en"],
    contacts: { email: "export@bursa-silk.example.com" },
    shippingInfo: {
      methods: ["DHL", "FedEx"],
      regionsServed: ["PL", "EU"],
      averageDaysToPoland: 6,
    },
    partnerCommissionPct: "7.00",
    tags: ["silk", "luxury", "bursa", "turkey", "fashion"],
    isActive: true,
    isFeatured: false,
  },

  // ─── EU suppliers ─────────────────────────────────────────────────────────
  {
    name: "Berlin Design Hub",
    slug: "berlin-design-hub",
    type: "eu",
    country: "DE",
    website: "https://berlin-design-hub.example.de",
    description: {
      ru: "Немецкие дизайнерские товары для дома и офиса — минималистичный стиль.",
      pl: "Niemieckie produkty designerskie do domu i biura — styl minimalistyczny.",
      en: "German designer home and office products — minimalist style.",
    },
    minimumOrderEur: 250,
    categories: ["home-decor", "office", "design", "stationery"],
    platforms: [],
    supportsDropship: true,
    isVerified: true,
    rating: "4.85",
    reviewCount: 156,
    languages: ["de", "en"],
    contacts: { email: "wholesale@berlin-design-hub.example.de" },
    shippingInfo: {
      methods: ["DHL", "DPD", "GLS"],
      regionsServed: ["PL", "EU"],
      averageDaysToPoland: 3,
      freeShippingAboveEur: 300,
    },
    partnerCommissionPct: "13.00",
    tags: ["design", "germany", "home-decor", "office", "minimalist"],
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Czech Crystal & Glass",
    slug: "czech-crystal-glass",
    type: "eu",
    country: "CZ",
    website: "https://czech-crystal.example.cz",
    description: {
      ru: "Богемский хрусталь и стекло ручной работы из Чехии — традиции с 1850 года.",
      pl: "Czeski kryształ i ręcznie robione szkło z Czech — tradycja od 1850 roku.",
      en: "Bohemian crystal and handmade glass from Czech Republic — tradition since 1850.",
    },
    minimumOrderEur: 350,
    categories: ["crystal", "glass", "luxury", "gifts", "home-decor"],
    platforms: [],
    supportsDropship: false,
    isVerified: true,
    rating: "4.95",
    reviewCount: 88,
    languages: ["cs", "en", "de"],
    contacts: { email: "export@czech-crystal.example.cz" },
    shippingInfo: {
      methods: ["DHL", "PPL"],
      regionsServed: ["PL", "EU"],
      averageDaysToPoland: 2,
    },
    partnerCommissionPct: "10.00",
    tags: ["crystal", "glass", "czech", "luxury", "gifts"],
    isActive: true,
    isFeatured: false,
  },
  {
    name: "Milano Cosmetics SRL",
    slug: "milano-cosmetics-srl",
    type: "eu",
    country: "IT",
    website: "https://milano-cosmetics.example.it",
    description: {
      ru: "Итальянская косметика премиум-класса — натуральные ингредиенты, Милан.",
      pl: "Włoskie kosmetyki premium — naturalne składniki, Made in Milano.",
      en: "Premium Italian cosmetics — natural ingredients, made in Milan.",
    },
    minimumOrderEur: 400,
    categories: ["cosmetics", "beauty", "skincare", "luxury", "italian"],
    platforms: [],
    supportsDropship: true,
    isVerified: true,
    rating: "4.80",
    reviewCount: 112,
    languages: ["it", "en"],
    contacts: { email: "b2b@milano-cosmetics.example.it" },
    shippingInfo: {
      methods: ["DHL", "UPS", "GLS"],
      regionsServed: ["PL", "EU"],
      averageDaysToPoland: 5,
      freeShippingAboveEur: 500,
    },
    partnerCommissionPct: "14.00",
    tags: ["cosmetics", "italy", "beauty", "luxury", "skincare"],
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Dutch Flowers Direct",
    slug: "dutch-flowers-direct",
    type: "eu",
    country: "NL",
    website: "https://dutch-flowers-direct.example.nl",
    description: {
      ru: "Оптовые поставки цветов и растений с аукциона Aalsmeer, Нидерланды.",
      pl: "Hurtowe dostawy kwiatów i roślin z aukcji Aalsmeer, Holandia.",
      en: "Wholesale flower and plant deliveries from Aalsmeer auction, Netherlands.",
    },
    minimumOrderEur: 150,
    categories: ["flowers", "plants", "gifts", "garden"],
    platforms: [],
    supportsDropship: false,
    isVerified: true,
    rating: "4.65",
    reviewCount: 55,
    languages: ["nl", "en", "de"],
    contacts: { email: "orders@dutch-flowers-direct.example.nl" },
    shippingInfo: {
      methods: ["refrigerated-truck", "DHL-Express"],
      regionsServed: ["PL", "EU"],
      averageDaysToPoland: 2,
    },
    partnerCommissionPct: "6.00",
    tags: ["flowers", "plants", "netherlands", "wholesale", "garden"],
    isActive: true,
    isFeatured: false,
  },

  // ─── DROPSHIP suppliers ───────────────────────────────────────────────────
  {
    name: "DropShip Master PL",
    slug: "dropship-master-pl",
    type: "dropship",
    country: "PL",
    website: "https://dropship-master-pl.example.com",
    description: {
      ru: "Дропшиппинг из Польши: 50 000+ SKU, интеграция с Baselinker и Allegro.",
      pl: "Dropshipping z Polski: 50 000+ SKU, integracja z Baselinker i Allegro.",
      en: "Polish dropshipping platform: 50,000+ SKUs, Baselinker and Allegro integration.",
    },
    minimumOrderEur: 0,
    categories: ["electronics", "home-decor", "fashion", "sports", "toys"],
    platforms: ["allegro"],
    supportsDropship: true,
    hasBaselinkerId: "DSM-PL-001",
    isVerified: true,
    rating: "4.55",
    reviewCount: 432,
    languages: ["pl", "en", "ru"],
    contacts: { email: "support@dropship-master-pl.example.com", telegram: "@dropshipmasterpl" },
    shippingInfo: {
      methods: ["InPost", "DPD", "DHL"],
      regionsServed: ["PL"],
      averageDaysToPoland: 1,
      freeShippingAboveEur: 0,
    },
    partnerCommissionPct: "5.00",
    tags: ["dropship", "poland", "allegro", "baselinker", "wholesale"],
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Global Drop EU",
    slug: "global-drop-eu",
    type: "dropship",
    country: "DE",
    website: "https://global-drop-eu.example.com",
    description: {
      ru: "Европейская платформа дропшиппинга с складами в Германии и Польше.",
      pl: "Europejska platforma dropshippingowa z magazynami w Niemczech i Polsce.",
      en: "European dropshipping platform with warehouses in Germany and Poland.",
    },
    minimumOrderEur: 0,
    categories: ["electronics", "gadgets", "home-decor", "sports"],
    platforms: ["allegro", "amazon_pl"],
    supportsDropship: true,
    hasBaselinkerId: "GDE-001",
    isVerified: true,
    rating: "4.40",
    reviewCount: 287,
    languages: ["de", "en", "pl"],
    contacts: { email: "partners@global-drop-eu.example.com" },
    shippingInfo: {
      methods: ["DHL", "DPD", "GLS", "InPost"],
      regionsServed: ["PL", "EU"],
      averageDaysToPoland: 2,
      freeShippingAboveEur: 50,
    },
    partnerCommissionPct: "5.00",
    tags: ["dropship", "europe", "germany", "wholesale"],
    isActive: true,
    isFeatured: false,
  },
  {
    name: "AliDrop Connect",
    slug: "alidrop-connect",
    type: "dropship",
    country: "CN",
    website: "https://alidrop-connect.example.com",
    description: {
      ru: "Дропшиппинг с AliExpress в Польшу — автоматизация заказов и трекинг.",
      pl: "Dropshipping z AliExpress do Polski — automatyzacja zamówień i śledzenie.",
      en: "AliExpress dropshipping to Poland — order automation and tracking.",
    },
    minimumOrderEur: 0,
    categories: ["electronics", "fashion", "home-decor", "accessories", "toys"],
    platforms: ["alibaba", "1688"],
    supportsDropship: true,
    isVerified: false,
    rating: "4.00",
    reviewCount: 178,
    languages: ["zh", "en", "pl", "ru"],
    contacts: { email: "support@alidrop-connect.example.com", telegram: "@alidropconnect" },
    shippingInfo: {
      methods: ["China Post", "ePacket", "DHL"],
      regionsServed: ["PL"],
      averageDaysToPoland: 20,
    },
    partnerCommissionPct: "5.00",
    tags: ["dropship", "aliexpress", "china", "automation"],
    isActive: true,
    isFeatured: false,
  },
  {
    name: "PrintPod Studio",
    slug: "printpod-studio",
    type: "dropship",
    country: "PL",
    website: "https://printpod-studio.example.pl",
    description: {
      ru: "Печать на заказ (Print-on-Demand): футболки, кружки, постеры с доставкой по Польше.",
      pl: "Druk na żądanie (Print-on-Demand): koszulki, kubki, plakaty z dostawą po Polsce.",
      en: "Print-on-Demand: t-shirts, mugs, posters delivered across Poland.",
    },
    minimumOrderEur: 0,
    categories: ["print-on-demand", "fashion", "gifts", "custom"],
    platforms: ["allegro"],
    supportsDropship: true,
    hasBaselinkerId: "POD-PL-003",
    isVerified: true,
    rating: "4.70",
    reviewCount: 521,
    languages: ["pl", "en"],
    contacts: { email: "hello@printpod-studio.example.pl" },
    shippingInfo: {
      methods: ["InPost", "Pocztex"],
      regionsServed: ["PL"],
      averageDaysToPoland: 3,
      freeShippingAboveEur: 100,
    },
    partnerCommissionPct: "15.00",
    tags: ["print-on-demand", "dropship", "poland", "custom", "gifts"],
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Zara Wholesale Alternative",
    slug: "zara-wholesale-alternative",
    type: "dropship",
    country: "ES",
    website: "https://zwa-fashion.example.es",
    description: {
      ru: "Испанская fast-fashion платформа с дропшиппингом по всей Европе.",
      pl: "Hiszpańska platforma fast-fashion z dropshippingiem na całą Europę.",
      en: "Spanish fast-fashion platform with European dropshipping.",
    },
    minimumOrderEur: 0,
    categories: ["fashion", "clothing", "women-fashion", "men-fashion"],
    platforms: [],
    supportsDropship: true,
    isVerified: false,
    rating: "4.20",
    reviewCount: 63,
    languages: ["es", "en"],
    contacts: { email: "dropship@zwa-fashion.example.es" },
    shippingInfo: {
      methods: ["DHL", "GLS"],
      regionsServed: ["PL", "EU"],
      averageDaysToPoland: 7,
    },
    partnerCommissionPct: "12.00",
    tags: ["fast-fashion", "dropship", "spain", "clothing"],
    isActive: true,
    isFeatured: false,
  },
  {
    name: "NaturalCare Dropship",
    slug: "naturalcare-dropship",
    type: "dropship",
    country: "PL",
    website: "https://naturalcare-dropship.example.pl",
    description: {
      ru: "Натуральная косметика и уход — дропшиппинг с польских производителей.",
      pl: "Naturalna kosmetyka i pielęgnacja — dropshipping od polskich producentów.",
      en: "Natural cosmetics and care — dropshipping from Polish manufacturers.",
    },
    minimumOrderEur: 0,
    categories: ["cosmetics", "beauty", "organic", "health", "natural"],
    platforms: ["allegro"],
    supportsDropship: true,
    hasBaselinkerId: "NC-DS-004",
    isVerified: true,
    rating: "4.85",
    reviewCount: 247,
    languages: ["pl", "en"],
    contacts: { email: "drop@naturalcare.example.pl", telegram: "@naturalcarepl" },
    shippingInfo: {
      methods: ["InPost", "DPD"],
      regionsServed: ["PL"],
      averageDaysToPoland: 1,
      freeShippingAboveEur: 80,
    },
    partnerCommissionPct: "15.00",
    tags: ["cosmetics", "natural", "dropship", "poland", "organic"],
    isActive: true,
    isFeatured: false,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Run seed
// ─────────────────────────────────────────────────────────────────────────────

async function seed(): Promise<void> {
  process.stdout.write(
    `[seed] Inserting ${SEED_SUPPLIERS.length} suppliers...\n`,
  );

  for (const supplierData of SEED_SUPPLIERS) {
    await db
      .insert(suppliers)
      .values(supplierData)
      .onConflictDoUpdate({
        target: suppliers.slug,
        set: {
          name: supplierData.name,
          type: supplierData.type,
          country: supplierData.country ?? null,
          description: supplierData.description ?? null,
          minimumOrderEur: supplierData.minimumOrderEur ?? null,
          categories: supplierData.categories ?? [],
          platforms: supplierData.platforms ?? [],
          supportsDropship: supplierData.supportsDropship ?? false,
          isVerified: supplierData.isVerified ?? false,
          rating: supplierData.rating ?? "0",
          reviewCount: supplierData.reviewCount ?? 0,
          languages: supplierData.languages ?? [],
          contacts: supplierData.contacts ?? null,
          shippingInfo: supplierData.shippingInfo ?? null,
          partnerCommissionPct: supplierData.partnerCommissionPct ?? null,
          tags: supplierData.tags ?? [],
          isActive: supplierData.isActive ?? true,
          isFeatured: supplierData.isFeatured ?? false,
          updatedAt: new Date(),
        },
      });
    process.stdout.write(`[seed]   + ${supplierData.name} (${supplierData.type})\n`);
  }

  process.stdout.write(`[seed] Done. ${SEED_SUPPLIERS.length} suppliers upserted.\n`);
}

seed()
  .catch((err: unknown) => {
    process.stderr.write(`[seed] Error: ${String(err)}\n`);
    process.exit(1);
  })
  .finally(() => {
    void pool.end();
  });
