apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecompilot

resources:
  - default-deny-all.yaml
  - services-policies.yaml

commonLabels:
  app.kubernetes.io/part-of: ecompilot
  app.kubernetes.io/component: network-policy
