// ─────────────────────────────────────────────────────────────────────────────
// EcomPilot PL — ksef-service: Drizzle ORM PostgreSQL schema
// Tables: invoices, ksef_sessions, ksef_credentials
// All monetary amounts stored in grosze (1 PLN = 100 grosze) as integers
// ─────────────────────────────────────────────────────────────────────────────

import {
  pgTable,
  uuid,
  text,
  integer,
  timestamp,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// ─────────────────────────────────────────────────────────────────────────────
// Enum value arrays — typed text columns with runtime safety
// ─────────────────────────────────────────────────────────────────────────────

export const INVOICE_TYPE_VALUES = ["VAT", "KOR", "ZAL", "ROZ", "UPR"] as const;
export const INVOICE_STATUS_VALUES = [
  "draft",
  "pending_ksef",
  "submitted",
  "accepted",
  "rejected",
  "offline",
] as const;
export const JPK_MARKER_VALUES = ["NrKSeF", "OFF", "BFK", "DI"] as const;
export const PAYMENT_METHOD_VALUES = [
  "przelew",
  "gotowka",
  "karta",
  "blik",
  "inna",
] as const;
export const SESSION_TYPE_VALUES = ["interactive", "batch"] as const;
export const SESSION_STATUS_VALUES = [
  "opening",
  "active",
  "closing",
  "closed",
  "error",
] as const;
export const AUTH_METHOD_VALUES = ["token", "xades"] as const;
export const KSEF_ENV_VALUES = ["test", "demo", "production"] as const;

export type InvoiceType = (typeof INVOICE_TYPE_VALUES)[number];
export type InvoiceStatus = (typeof INVOICE_STATUS_VALUES)[number];
export type JpkMarker = (typeof JPK_MARKER_VALUES)[number];
export type PaymentMethodDb = (typeof PAYMENT_METHOD_VALUES)[number];
export type SessionType = (typeof SESSION_TYPE_VALUES)[number];
export type SessionStatus = (typeof SESSION_STATUS_VALUES)[number];
export type AuthMethod = (typeof AUTH_METHOD_VALUES)[number];
export type KsefEnvDb = (typeof KSEF_ENV_VALUES)[number];

// ─────────────────────────────────────────────────────────────────────────────
// invoices
// Core table storing all KSeF invoices generated by the service.
// Monetary amounts in grosze (integer). XML stored as text for audit trail.
// ─────────────────────────────────────────────────────────────────────────────

export const invoices = pgTable(
  "ksef_invoices",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    /** Internal user ID (references auth-service user) */
    userId: uuid("user_id").notNull(),

    /** Seller's sequential invoice number (e.g. "FV/2026/01/0001") */
    invoiceNumber: text("invoice_number").notNull(),

    /** FA(3) invoice type: VAT | KOR | ZAL | ROZ | UPR */
    invoiceType: text("invoice_type").$type<InvoiceType>().notNull().default("VAT"),

    /** Processing status in the KSeF pipeline */
    status: text("status").$type<InvoiceStatus>().notNull().default("draft"),

    /** Full FA(3) XML content — stored for audit, UPO validation, and resubmission */
    xmlContent: text("xml_content").notNull(),

    /**
     * KSeF system invoice number (e.g. "9999999999-20260401-ABCDEF01-01")
     * Assigned by KSeF after acceptance. Null until accepted.
     */
    ksefNumber: text("ksef_number"),

    /**
     * KSeF reference number returned from POST /invoices.
     * Used to poll status and retrieve UPO.
     */
    ksefReferenceNumber: text("ksef_reference_number"),

    /** Seller's NIP (10 digits) */
    sellerNip: text("seller_nip").notNull(),

    /** Buyer's NIP — null for B2C or foreign buyers */
    buyerNip: text("buyer_nip"),

    /** Net amount in grosze */
    netAmount: integer("net_amount").notNull(),

    /** VAT amount in grosze */
    vatAmount: integer("vat_amount").notNull(),

    /** Gross amount in grosze (net + VAT) */
    grossAmount: integer("gross_amount").notNull(),

    /**
     * JPK_V7 marker:
     *   NrKSeF — accepted, has KSeF reference number
     *   OFF    — issued in offline mode (KSeF unavailable)
     *   BFK    — excluded from KSeF (B2C without request, OSS/IOSS)
     *   DI     — digital services (OSS/IOSS rules)
     */
    jpkMarker: text("jpk_marker").$type<JpkMarker>(),

    /** GTU classification codes for line items (array stored as text[]) */
    gtuCodes: text("gtu_codes").array(),

    /** Payment method used for this invoice */
    paymentMethod: text("payment_method").$type<PaymentMethodDb>().notNull().default("przelew"),

    /** Invoice issue date (YYYY-MM-DD) */
    issueDate: text("issue_date").notNull(),

    /**
     * Timestamp when KSeF accepted the invoice.
     * Null until status = 'accepted'.
     */
    ksefAcceptedAt: timestamp("ksef_accepted_at", { withTimezone: true }),

    /**
     * Deadline for offline submission (7 days from issue date, per MF regulation).
     * Only set when status = 'offline'.
     */
    offlineSubmitDeadline: timestamp("offline_submit_deadline", { withTimezone: true }),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),

    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    userIdIdx: index("invoices_user_id_idx").on(table.userId),
    invoiceNumberIdx: uniqueIndex("invoices_invoice_number_idx").on(table.invoiceNumber),
    statusIdx: index("invoices_status_idx").on(table.status),
    ksefReferenceNumberIdx: uniqueIndex("invoices_ksef_reference_number_idx").on(
      table.ksefReferenceNumber,
    ),
    sellerNipIdx: index("invoices_seller_nip_idx").on(table.sellerNip),
    issueDateIdx: index("invoices_issue_date_idx").on(table.issueDate),
    jpkMarkerIdx: index("invoices_jpk_marker_idx").on(table.jpkMarker),
    createdAtIdx: index("invoices_created_at_idx").on(table.createdAt),
    offlineDeadlineIdx: index("invoices_offline_deadline_idx").on(
      table.offlineSubmitDeadline,
    ),
  }),
);

export type Invoice = typeof invoices.$inferSelect;
export type NewInvoice = typeof invoices.$inferInsert;

// ─────────────────────────────────────────────────────────────────────────────
// ksef_sessions
// Tracks interactive and batch KSeF API sessions.
// Sessions are created at submission time and closed after all invoices are sent.
// ─────────────────────────────────────────────────────────────────────────────

export const ksefSessions = pgTable(
  "ksef_sessions",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    /** Internal user ID who opened the session */
    userId: uuid("user_id").notNull(),

    /** Session type: interactive (real-time) or batch (ZIP upload) */
    sessionType: text("session_type").$type<SessionType>().notNull(),

    /**
     * KSeF-assigned session reference number.
     * Returned by POST /sessions/online or POST /sessions/batch.
     */
    referenceNumber: text("reference_number").notNull().unique(),

    /** Current session lifecycle status */
    status: text("status").$type<SessionStatus>().notNull().default("opening"),

    /** KSeF environment this session was opened against */
    environment: text("environment").$type<KsefEnvDb>().notNull(),

    /** Session token returned after auth challenge-response */
    sessionToken: text("session_token"),

    /** ISO 8601 datetime when the session token expires */
    tokenExpiresAt: timestamp("token_expires_at", { withTimezone: true }),

    openedAt: timestamp("opened_at", { withTimezone: true })
      .notNull()
      .defaultNow(),

    closedAt: timestamp("closed_at", { withTimezone: true }),
  },
  (table) => ({
    userIdIdx: index("ksef_sessions_user_id_idx").on(table.userId),
    referenceNumberIdx: uniqueIndex("ksef_sessions_reference_number_idx").on(
      table.referenceNumber,
    ),
    statusIdx: index("ksef_sessions_status_idx").on(table.status),
    environmentIdx: index("ksef_sessions_environment_idx").on(table.environment),
    openedAtIdx: index("ksef_sessions_opened_at_idx").on(table.openedAt),
  }),
);

export type KsefSessionRow = typeof ksefSessions.$inferSelect;
export type NewKsefSession = typeof ksefSessions.$inferInsert;

// ─────────────────────────────────────────────────────────────────────────────
// ksef_credentials
// Stores per-user KSeF authentication credentials (encrypted at rest).
// Each user can have credentials for multiple environments.
// SECURITY: encryptedToken is AES-256-GCM encrypted; never store plaintext.
// ─────────────────────────────────────────────────────────────────────────────

export const ksefCredentials = pgTable(
  "ksef_credentials",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    /** Internal user ID */
    userId: uuid("user_id").notNull(),

    /** Target KSeF environment */
    environment: text("environment").$type<KsefEnvDb>().notNull(),

    /**
     * Authentication method:
     *   token  — API token (default for programmatic access)
     *   xades  — XAdES qualified electronic signature
     */
    authMethod: text("auth_method").$type<AuthMethod>().notNull().default("token"),

    /**
     * AES-256-GCM encrypted token or certificate.
     * Format: "<base64-iv>:<base64-tag>:<base64-ciphertext>"
     * NEVER store the plaintext value here.
     */
    encryptedToken: text("encrypted_token").notNull(),

    /** NIP associated with these credentials */
    nipNumber: text("nip_number").notNull(),

    /** Whether these are the active credentials for this user+environment combination */
    isActive: text("is_active").notNull().default("true"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),

    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    userIdIdx: index("ksef_credentials_user_id_idx").on(table.userId),
    userEnvIdx: uniqueIndex("ksef_credentials_user_env_idx").on(
      table.userId,
      table.environment,
    ),
    nipIdx: index("ksef_credentials_nip_idx").on(table.nipNumber),
  }),
);

export type KsefCredential = typeof ksefCredentials.$inferSelect;
export type NewKsefCredential = typeof ksefCredentials.$inferInsert;

// ─────────────────────────────────────────────────────────────────────────────
// Relations
// ─────────────────────────────────────────────────────────────────────────────

export const invoicesRelations = relations(invoices, () => ({}));
export const ksefSessionsRelations = relations(ksefSessions, () => ({}));
export const ksefCredentialsRelations = relations(ksefCredentials, () => ({}));
