apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecompilot

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: community-service
  app.kubernetes.io/part-of: ecompilot
