// ─────────────────────────────────────────────────────────────────────────────
// EcomPilot PL — content-service
// AWS S3 service: upload, signed URL generation, delete
// ─────────────────────────────────────────────────────────────────────────────

import {
  S3Client,
  PutObjectCommand,
  DeleteObjectCommand,
  HeadObjectCommand,
  type PutObjectCommandInput,
} from "@aws-sdk/client-s3";
import { getSignedUrl as awsGetSignedUrl } from "@aws-sdk/s3-request-presigner";
import { GetObjectCommand } from "@aws-sdk/client-s3";
import { env } from "../config/env.js";

// ─────────────────────────────────────────────────────────────────────────────
// Client singleton
// ─────────────────────────────────────────────────────────────────────────────

let _client: S3Client | null = null;

function getClient(): S3Client {
  if (_client !== null) return _client;
  _client = new S3Client({
    region: env.AWS_REGION,
    credentials: {
      accessKeyId: env.AWS_ACCESS_KEY_ID,
      secretAccessKey: env.AWS_SECRET_ACCESS_KEY,
    },
  });
  return _client;
}

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export interface UploadResult {
  readonly key: string;
  /** Public CDN URL (not signed — suitable for long-lived cached assets) */
  readonly cdnUrl: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Key builder
// Format: content/{userId}/{type}/{uuid}.webp
// ─────────────────────────────────────────────────────────────────────────────

export function buildContentKey(
  userId: string,
  type: "thumbnail" | "background_removal",
  fileId: string,
): string {
  return `content/${userId}/${type}/${fileId}.webp`;
}

// ─────────────────────────────────────────────────────────────────────────────
// uploadBuffer
// ─────────────────────────────────────────────────────────────────────────────

export async function uploadBuffer(
  buffer: Buffer,
  key: string,
  contentType: string,
): Promise<UploadResult> {
  const params: PutObjectCommandInput = {
    Bucket: env.AWS_S3_BUCKET,
    Key: key,
    Body: buffer,
    ContentType: contentType,
    // Assets generated by DALL-E / Sharp are immutable — safe to cache forever
    CacheControl: "max-age=31536000, immutable",
    // Metadata for debugging
    Metadata: {
      "uploaded-by": "content-service",
      "content-service-version": process.env["npm_package_version"] ?? "0.0.0",
    },
  };

  await getClient().send(new PutObjectCommand(params));

  const cdnUrl = `${env.CDN_URL}/${key}`;
  return { key, cdnUrl };
}

// ─────────────────────────────────────────────────────────────────────────────
// getSignedUrl
// Returns a pre-signed GET URL with configurable TTL (default 1 hour)
// ─────────────────────────────────────────────────────────────────────────────

export async function getSignedUrl(
  key: string,
  ttlSeconds = 3_600,
): Promise<string> {
  const command = new GetObjectCommand({
    Bucket: env.AWS_S3_BUCKET,
    Key: key,
  });

  return awsGetSignedUrl(getClient(), command, {
    expiresIn: ttlSeconds,
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// deleteObject
// ─────────────────────────────────────────────────────────────────────────────

export async function deleteObject(key: string): Promise<void> {
  await getClient().send(
    new DeleteObjectCommand({
      Bucket: env.AWS_S3_BUCKET,
      Key: key,
    }),
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// objectExists — convenience helper for idempotency checks
// ─────────────────────────────────────────────────────────────────────────────

export async function objectExists(key: string): Promise<boolean> {
  try {
    await getClient().send(
      new HeadObjectCommand({ Bucket: env.AWS_S3_BUCKET, Key: key }),
    );
    return true;
  } catch {
    return false;
  }
}
